const CREATE_TYPE = "POST/CREATE_TYPE";
const FETCH_TYPES = "GET/FETCH_TYPES";

const CREATE_BRAND = "POST/CREATE_BRAND";
const FETCH_BRANDS = "GET/FETCH_BRANDS";

const CREATE_DEVICE = "POST/CREATE_DEVICE";
const FETCH_DEVICES = "GET/FETCH_DEVICES";
const FETCH_ONE_DEVICE = "GET/FETCH_ONE_DEVICE";

const REGISTRATION = "POST/REGISTER";
const LOGIN = "POST/LOGIN";
const CHECK = "GET/CHECK";

const CART = "GET/CART";
const ADD_PRODUCT_TO_CART = "POST/ADD_PRODUCT_TO_CART";

const FAVORITES = "GET/FAVORITES";
const ADD_PRODUCT_TO_FAVORITE = "POST/ADD_PRODUCT_TO_FAVORITE";
